QQbject superclasses implementation
viperleed/viperleed pull request #208
Opened 2024-05-07 09:43 UTC by FlorianDoerr

Basic implementation of the new superclasses for ViPErLEED measurement objects.

Fixes #197

2024-05-18 08:42 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +from viperleed.guilib.measure.hardwarebase import QMetaABC
Perhaps it would be cleaner to also move QMetaABC in this module

2024-05-18 08:44 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +class QObjectABCErrors(ViPErLEEDErrorEnum):
Since these are only settings-related errors, I'd probably modify the class name (and docstring) to reflect this more clearly.

2024-05-18 08:46 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    # information about the error which occurred.
```suggestion
    # information about the error in the form (code, message).
```

2024-05-18 08:48 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            _name = self.__class__.__name__
```suggestion
            _name = type(self).__name__
```

2024-05-18 08:51 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            If no default settings were detected.
Missing TOO_MANY doc

2024-05-18 08:57 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +                tmp.append((settings_file, conformity))
```suggestion
        is_matching = (cls.is_matching_default_settings if default
                       else cls.is_matching_settings)
        for settings_file in settings_files:
            config = ConfigParser()
            config.read(settings_file)
            conformity = is_matching(obj_info, config, exact_match)
            if conformity:
                tmp.append((settings_file, conformity))
```

2024-05-18 08:58 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        tmp = []
`tmp` is not a great name. I'd call it in a way that makes sense with what it will contain. E.g., `files_and_scores`.

2024-05-18 08:59 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        settings_files = directory.glob('**/*.ini')
```suggestion
        settings_files = Path(directory).resolve().glob('**/*.ini')
```

2024-05-18 09:01 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        settings_files = directory.glob('**/*.ini')
Also, I thought you had mentioned that we should be a bit careful about recursive globbing in case people select their user folder to be a parent of the viperleed repository, which contains the defaults. Perhaps you can filter out from these settings files those that are in the defaults, in case `default` is `False`?

2024-05-18 09:04 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        obj_settings_files = []
You don't need to define it beforehand, as you anyway override it below.
```suggestion
```

2024-05-18 09:05 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        path_to_config : Path or ''
I would return `None` rather than empty. Makes more sense for a failure condition. Alternatively, consider raising an exception.

2024-05-18 09:08 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            be used to check settings.
```suggestion
        obj_info : SettingsInfo
            The information that should be used to check `config`.
```

2024-05-18 09:09 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            If True, the information is matched exactly.
```suggestion
```

Redundant

2024-05-18 09:11 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    def find_default_settings(self, find_from, exact_match=False):
I would rename `exact_math` to `match_exactly` everywhere. I think it conveys better the fact that this is a bool.

2024-05-18 09:12 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    def is_matching_settings(cls, obj_info, config, exact_match):
I'd suggest `is_matching_user_settings` to make the intent more obvious.

2024-05-18 09:13 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            order of their significance.
```suggestion
            order of their significance. This return value is used
            to determine the best-matching settings files when
            multiple files are found.
```

2024-05-18 09:16 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        obj_info : SettingsInfo
See my suggestions for the docstring of the other method.

2024-05-18 09:16 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            conformity. The order of the values in the tuple is the
```suggestion
            conformity. The order of the items in the tuple is the
```

2024-05-18 09:17 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        run time.
```suggestion
        Reimplementations can add additional mandatory settings
        at runtime.
```

2024-05-18 09:18 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        run time.
I would describe the base implementation in a few words.

2024-05-18 09:21 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            )
```suggestion
        file = self.settings.last_file
        widget.setText(file.stem if file else 'None')
```

2024-05-18 09:24 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        handler = SettingsHandler(self.settings)
I think here it would be nicer to consider a few situations and raise explicitly:
  1. `not self.settings`
  2. `self.settings.last_file` is one of the defaults

2024-05-18 09:29 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            tooltip=str(self.settings.last_file),
```suggestion
            tooltip=str(file) if file else None,
```

2024-05-18 09:33 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        """
I would probably make the method that replaces deprecated stuff a method of the ViPErLEEDSettings class.

2024-05-18 09:35 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        """Set new settings for this instance.
I would also explicitly mention that this is the same method used in the setter of the `settings` `@property`.

2024-05-18 09:37 UTC, michele-riva commented on guilib/measure/hardwarebase.py
>      in case the no config file was found with the original arguments
```suggestion
    in case no settings file was found with the original arguments
```

2024-05-18 09:42 UTC, michele-riva commented on guilib/measure/hardwarebase.py
>              )
I cannot add a comment for L264, but could you change it to `if _clicked is btn:`?

2024-05-18 09:43 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +    This method must be executed in the main GUI thread.
```suggestion
    This function must be executed in the main GUI thread.
```

2024-05-18 09:45 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        exact_match : bool, optional
Also modify this one to `match_exactly`.

2024-05-18 09:49 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +            the path to the _defaults directory.
Given that you now have added the `default` kwarg, I would perhaps adapt which path is the default depending on it. An alternative would be to decide whether the value of `default` is True based on the value of `directory`: if it is the `DEFAULTS_PATH` then we're looking for a default. In this case, you could simply remove the new kwarg.

2024-05-18 09:54 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +    obj_name = obj_info.unique_name
```suggestion
```
Used only once

2024-05-18 09:54 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        f"{obj_name} in {directory} and subfolders.\n"
```suggestion
        f"{obj_info.unique_name} in {directory} and subfolders.\n"
```

2024-05-18 09:58 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +    """A container for information about settings of objects.
I would say here that instances of this class should be constructed such that they contain enough information to identify settings that are appropriate, for example, for a device.

2024-05-18 10:12 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    # Contains the busy state the device changed to.
```suggestion
    # Contains the new busy state of the device.
```

2024-05-18 10:14 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        # performed in the calling thread.
I would place the comment in the docstring, perhaps, as it is quite important. You can also suggest to instead connect a signal or invoke the set_busy slot.

2024-05-18 10:16 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    def get_busy(self):
I would explicitly say that this method is called directly in the getter of the busy @property. Subclasses that override this method to modify also the value returned by self.busy.

2024-05-18 10:16 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        True if the instance is busy.
indent

2024-05-18 10:18 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        if was_busy is not is_busy:
```suggestion
        if was_busy != is_busy:
```
just in case someone else uses some other bool-like, like np.bool

2024-05-18 10:19 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        SettingsInfo class is located in the hardwarebase module. Each
Would it make sense to move the SettingsInfo in this module instead?

2024-05-18 10:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        .more information as a dict.
I would also reiterate here the fact that the information returned for a device in the SettingsInfo should be enough to retrieve a settings file compatible with the device, i.e., one that allows to establish communication with the device.

2024-05-18 10:26 UTC, michele-riva commented on guilib/measure/classes/datapoints.py
> +from viperleed.guilib.measure.hardwarebase import ViPErLEEDErrorEnum
Alphabetic sorting, including capitalization: Capital letters come earlier in character tables.

2024-05-18 10:31 UTC, michele-riva commented on guilib/measure/classes/settings.py
>          except (TypeError, MissingSettingsFileError):
```suggestion
        except (TypeError, MissingSettingsFileError) as exc:
```

2024-05-18 10:31 UTC, michele-riva commented on guilib/measure/classes/settings.py
> +            raise NoSettingsError(f"{cls.__name__}: could not load settings.")
```suggestion
            raise NoSettingsError(f"{cls.__name__}: could not load settings.") from exc
```

2024-05-18 10:33 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +                      'instead.')
I'm wondering if this should be an error or should simply raise. It means someone programmed it wrong.

2024-05-18 10:35 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    """Abstract base class of measurement objects with settings."""
I think it would be good to add some words of instruction on subclassing this. I would especially refer to the attributes that are defined in `__init__` and how to use them.

2024-05-18 10:36 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        True if the controller is busy.
indent

2024-05-18 10:38 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        """Return whether the controller is busy.
I would add a note on the fact that controllers are always busy as long as their serial is.

2024-05-18 10:42 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +            self.busy_changed.emit(self.busy)
Why not `super().set_busy(is_busy)`? Then you can also delete L268.

2024-05-18 10:45 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +            The new settings. new_settings (or the default) will be
```suggestion
            The new settings. new_settings will be
```

2024-05-18 11:40 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        serial_cls_name = self._settings.get('controller', 'serial_class',
May I ask you to split this part of the method -- from here to the end -- into a dedicated private one? Something like: _update_serial_from_settings(self). You can probably not catch the ValueError raised in base.class_from_name in the _update_serial_..., and keep catching it over here.

2024-05-18 11:49 UTC, michele-riva commented on guilib/measure/controller/abc.py
>          be the controller name and it's address to make it unique.
```suggestion
        holding .more information about the device. .unique_name may
        be contain the controller name and it's address to make it unique.
```

2024-05-18 12:42 UTC, michele-riva commented on guilib/measure/camera/abc.py
>          holding additional information about the device. If there is
Like for the other list_devices, I would be clearer about the fact that the SettingsInfo returned should have enough information to establish commuincation with the camera.

2024-05-18 12:43 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +    )
two separate lines perhaps?

2024-05-18 14:47 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        if obj_info.more['name'] == camera_class:
```suggestion
        if cls.__name__ == camera_class:
```
I don't think we need to add the class name to the more dict. It's readily available.

2024-05-18 14:50 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +            if bool(camera_name.match(obj_info.unique_name)):
```suggestion
            if camera_name.match(obj_info.unique_name):
```
Match returns None if it does not match

2024-05-18 14:57 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        if camera_name and not exact_match:
Maybe turn this bit around:


```
        if exact match and camera_name == obj_info.unique_name:
             return (1,)
        camera_name_re = 
```

2024-05-18 15:01 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        return ()
```suggestion
        return (1,) if cls.__name__ == camera_class else ()
```

2024-05-19 04:39 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            the matching check for a default settings is performed.
I would explicitly name the methods. This makes it clearer.
```suggestion
            is_matching_default_settings is used to determine
            whether a configuration file is appropriate. If False,
            is_matching_user_settings is used instead.
```

2024-05-19 04:55 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            )
I'm not sure I like this business with the string version. I don't think we even need it: the only name that makes sense here is the class name. We always have access to this, without the need to store it in `find_from`. We could allow `find_from` to also be `None`, and make it optional for this method only. It will be up to the `is_matching_..._settings` to do the right thing. I would suggest having an `is_settings_for_this_class(cls, config)` abstract classmethod that is called in `find_matching_settings_files` before the other checkers (and applies to both defaults and not). E.g.,

```python
for file in settings_files:
    ... read parser ...
    if not cls.is_settings_for_this_class(config):
        continue
    ... check the rest ...
```

This would also simplify the methods in the concrete subclasses.

2024-05-19 05:19 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            find_matching_settings_files in self. If it is
I think it would be better to directly name `is_matching_default_settings` here, as the `find_matching_settings_files` is not going to be reimplemented. If you follow my suggestion below about `is_settings_for_this_class` then I would also name that new method here.

2024-05-19 05:25 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +                        'Invalid settings for instance of {}. Required '
Do we really need this extra format argument? We can always use `.sender()` to determine who caused the error (and we do so anyway). (Also applies to the next one.)

2024-05-19 05:32 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        return ()
If you follow my suggestion concerning the `is_settings_for_this_class` method (see `abc`), you could simply reuse this code there, as:

```python
    @classmethod
    def is_settings_for_this_class(cls, config):
        """...docstring..."""
        camera_class = config.get('camera_settings', 'class_name',
                                  fallback=None)
        return cls.__name__ == camera_class

    @classmethod
    def is_matching_default_settings(cls, *_):
        """...docstring..."""
        return (1,)
```

The latter is because the settings always match if they're for the class.

2024-05-19 05:55 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        return ()
```suggestion
        camera_name = config.get('camera_settings', 'device_name',
                                 fallback=None)
        if exact_match:
            return (1,) if obj_info.unique_name == camera_name else ()
        if camera_name is None:
            # Can't be a good file if there is no device_name.
            return ()
        camera_name_re = _device_name_re(camera_name)
        return (1,) if camera_name_re.match(obj_info.unique_name) else ()
```

Turned around a little bit to avoid as much as possible nested ifs. Should be functionally identical, but please check.

2024-05-19 05:57 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +from viperleed.guilib.measure.hardwarebase import _device_name_re
Make name public in hardwarebase. You should never import private attributes.

2024-05-19 06:17 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        invalid = settings.has_settings(('controller', 'firmware_version'))
I would revert the changes about the version business. I'm not happy with (i) the fact that we don't emit information about what was the problem (the user will just see 'settings invalid' and not know what to do about it), and (ii) you now risk NameError at L331 under multiple conditions, as you do not return early any more.

2024-05-19 06:21 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        handler.add_from_handler(super().get_settings_handler())
Is this the right place, or should you rather do it before? This will show the file name not at the top.

2024-05-19 06:23 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        controller_class = config.get('controller', 'controller_class',
The part about matching class could be removed from these two methods and moved as-is to `is_settings_for_this_class`.

2024-05-19 06:25 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        return ()
```suggestion
        if obj_info.more['name'] != controller_name:
            return ()
        if obj_info.more['firmware'] == firmware_ver:
            return (firmware_ver.minor,)
        if (not exact_match
              and obj_info.more['firmware'].major == firmware_ver.major):
            # For a tolerant match checking the firmware major
            # is good enough, as settings with the same major
            # are bound to be at least partially compatible.
            return (firmware_ver.minor,)
        return ()
```

2024-05-19 06:31 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        firmware_ver = base.Version(ver or '0.0')
```suggestion
        firmware_ver = base.Version(
            config.get('controller', 'firmware_version', fallback='0.0')
            )
```

2024-05-19 06:33 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        firmware_ver = base.Version(ver) if ver else base.Version('0.0')
```suggestion
        firmware_ver = base.Version(
            config.get('controller', 'firmware_version', fallback='0.0')
            )
```

2024-05-19 06:52 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        firmware_matches = obj_info.more.get('firmware') == firmware_ver
To handle the None case I suggest in abc:
```suggestion
        firmware_matches = (False if obj_info is None
                            else obj_info.more.get('firmware') == firmware_ver)
```

2024-05-19 06:53 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +    def is_matching_settings(cls, obj_info, config, exact_match):
In this case, I think we should instead raise hard (e.g., `TypeError`) if `obj_info` is `None` (see my suggestion in `abc`), as this means that there is a bug.

2024-05-19 06:56 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +            If True, the information is matched exactly.
I think you should be more specific. The current implementation uses non-exact matching only for the firmware version. The name is however always matched exactly.

2024-05-19 06:57 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +            be used to check settings.
Write down which values are expected to be defined.

2024-05-19 06:59 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +            order of their significance.
I think here you want to be more specific in describing what you are actually returning.

2024-05-19 07:00 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +            order of their significance.
Be more specific as to what you return.

2024-05-19 07:00 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +            be used to check settings.
Describe what you use of this object.

2024-05-19 07:05 UTC, michele-riva commented on guilib/measure/dialogs/badpxfinderdialog.py
> +            camera_cls, camera_info, directory=_default_config_path(),
I cannot add a comment where _default_config_path() is defined, but perhaps would be nice to rename it to _user_config_path() to avoid confusion with the DEFAULTS.

2024-05-19 07:09 UTC, michele-riva commented on guilib/measure/dialogs/badpxfinderdialog.py
>  from viperleed.guilib.measure import camera as _m_camera
Having a look at where this is now used, I guess one could instead
```suggestion
from viperleed.guilib.measure.camera import badpixels
```

Could you please check that this does not give cyclic imports?

2024-05-19 07:10 UTC, michele-riva commented on guilib/measure/dialogs/badpxfinderdialog.py
>  from viperleed.guilib.measure.classes import settings as _m_settings
Also on this one, it would be great to just import the right stuff, as long as we don't have cyclic import issues:
```suggestion
from viperleed.guilib.measure.classes.settings import SystemSettings
from viperleed.guilib.measure.classes.settings import ViPErLEEDSettings
```

2024-05-19 07:17 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +            Default is False.
I would rather subclass the `SettingsDialogOption` to a `StaticSettingsDialogOption` as this is somewhat fundamentally different. For one, it always is read-only.

2024-05-19 07:20 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +                    option.set_(self.__config[sec_name][opt_name])
```suggestion
                if isinstance(option, StaticSettingsDialogOption):
                    continue
                option.set_(self.__config[sec_name][opt_name])
```

2024-05-19 07:21 UTC, michele-riva commented on guilib/measure/measurement/energy_calibration.py
>  from viperleed.guilib.measure.classes.settings import NotASequenceError
alphabetic sort

2024-05-19 07:22 UTC, michele-riva commented on guilib/measure/measurement/time_resolved.py
>  from viperleed.guilib.measure import hardwarebase as base
I'd move this up to the beginning

2024-05-19 07:23 UTC, michele-riva commented on guilib/measure/uimeasurement.py
>                                         title="System settings"),
indent

2024-05-19 07:24 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +            device_name = settings_info.unique_name
```suggestion
        device_name = settings_info.more['name'] or settings_info.unique_name
```

2024-05-19 07:27 UTC, michele-riva commented on guilib/measure/uimeasurement.py
>          # Find an appropriate settings file, searching in the default
```suggestion
        # Find an appropriate settings file, searching in the user
```

2024-05-19 07:32 UTC, michele-riva commented on hardware/arduino/viper-ino/README.md
> +	the **major** of the firmware version.
```suggestion
   the **major** of the firmware version.
```
spaces instead of tabs everywhere. Also below

2024-05-19 08:58 UTC, michele-riva commented on guilib/measure/measurement/abc.py
>              # TODO: probably good to clean up secondaries and cameras!
I cannot add a comment on L348-349, but the indentation is wrong there (one space too few).

2024-05-19 09:02 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +            camera.busy_changed.disconnect(self.__check_preparation_finished)
Since now all signals are called the same, you could just:
```python
        for device in self.devices:
            device.busy_changed.disconnect(self.__check_preparation_finished)
```

2024-05-19 09:11 UTC, michele-riva commented on guilib/measure/serial/abc.py
> +        return ()
If this is the way we want it to happen, then we should raise. However, I'm not sure that's the way to go. I personally think that the viperleedserial could do some checking. The same is true for the next method. Let's discuss.

2024-05-19 09:15 UTC, michele-riva commented on guilib/measure/serial/viperleedserial.py
> +from viperleed.guilib.measure.serial.abc import ExtraSerialErrors
alphabetic sort

2024-10-05 06:23 UTC, michele-riva requested changes
Great work @FlorianDoerr. A few small changes, but we're almost there!

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +from viperleed.guilib.measure.classes.settings import ViPErLEEDSettings
```suggestion
from viperleed.guilib.measure.classes.settings import (
    NoDefaultSettingsError,
    NoSettingsError,
    SettingsError,
    TooManyDefaultSettingsError,
    ViPErLEEDSettings,
    )
```

Since you anyway have to have the "(\n...\n)" part, you can merge all the imports from the module in there. The main reason to have "one import per line" is to ease maintenance: when a new imported object is added (or removed, or changed) this affects only one line of the imports, and you don't have to shuffle the others around. When you use the "(\n...\n)" syntax (because one of the imported names does not fit on a single line), then you already are set to have only one imported quantity per line. (Notice that all items have their comma at the end, including the last one: adding or removing one still only affects one line of code.)

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    error_occurred = qtc.pyqtSignal(tuple)
It may be nice to give this one an `emit_error` method like so:
```suggestion
class QObjectWithError(qtc.QObject):                                            # TODO: The Measure class was meant to inherit from this class. Due to double inheritance from QObject this is not possible through standard inheritance.
    """Base class of measurement objects with error detection."""

    # Emitted whenever an error has been detected. Contains
    # information about the error in the form (code, message).
    error_occurred = qtc.pyqtSignal(tuple)

    emit_error = hardwarebase.emit_error
```

This way we can then do `self.emit_error(...)`. I believe the `hardwarebase` function takes the object as the first argument, so defining the method like above should simply work. Consider whether it makes sense to have an explicit `def emit_error` instead if `help(QObjectWithErrors.emit_error)` is not clear enough.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    uses_default_settings : bool
This is probably not a private one

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        method.
What I gather from this docstring is that subclasses are not supposed to use this attribute. If this is the case, then I would remove its documentation and rather place a comment where you define it. If instead, subclasses may use this, then I would suggest to add here more details of "when" it makes sense to use this rather than the `@property`

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        before the settings of an instance are set.
```suggestion
        before the settings of an instance are set, i.e., before
        self.settings = self._settings_to_load (or, equivalently,
        self.set_settings(self._settings_to_load). 
```

I would also be explicit here and say that the base-class implementation does not load the settings. Subclasses must do that. For the same reason, I'd suggest to make this an `@abstractmethod`.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            Unused positional arguments.
```suggestion
            Unused positional arguments. Subclasses may accept positional arguments.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            a suitable default is searched.
```suggestion
            a suitable default is searched. Default it None.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            Unused keyword arguments.
```suggestion
            Unused keyword arguments. Subclasses may accept keyword-only arguments.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            Unused positional arguments.
Actually, now that I see this, it is not true that you don't use it (same is true for `**kwargs`): you call `super().__init__(*args, **kwargs)`. So I'd rather say that these are passed along unaltered to the first parent class in the inheritance tree. (Applies to kwargs below too.)

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    def check_before_getting_settings_handler(self):
```suggestion
    def check_creating_settings_handler_is_possible(self):
```

(Or similar)

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        """Check if getting a SettingsHandler is possible."""
```suggestion
        """Raise if it is not possible to produce a SettingsHandler."""
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            in self. Default is None.
```suggestion
            settings is up to the is_settings_for_this_class() and
            is_matching_default_settings() methods. Default is None.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            in self. Default is None.
What happens if `None` or not given?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        find_from : SettingsInfo or None, optional
```suggestion
        find_from : SettingsInfo, optional
```

Consider removing `None` from the parameter types if giving `None` has no special effect other than "skipping something". Of course document what happens if not given (see below).

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            Default is False.
Perhaps a few words on what it means to give `False` here?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        # be used to find settings from default name.
Is this comment still true? I don't see a dummy `SettingsInfo` here.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        self.uses_default_settings = False
It may be a bit risky to expose this as an editable attribute. Perhaps have a `self._uses_default_settings` and an read-only public `@property` is better?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            )
Is there any occasion in which a call with `DEFAULTS_PATH` and `default=False` makes sense? If not, then probably we don't need the `default` kwarg. If it doesn't, then we could use `directory == DEFAULTS_PATH` to discern whether we want a default in `self.find_matching_settings_file`.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            )
Also, add an extra comma at the end.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        method and call super().find_default_settings in the end.
```suggestion
        This method may be extended in subclasses. Make
        sure to call super().find_default_settings at the end.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            The location in which to look for configuration files.
```suggestion
            The location in which to look for configuration files.
            Settings files are searched in directory and all its subfolders.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            is_matching_user_settings is used instead.
See my comment above. If we go the route of using `directory == DEFAULTS_PATH`, make sure to update the description of `directory` accordingly.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            A list of the found settings paths that contain appropriate
```suggestion
            A list of the paths to settings files that contain appropriate
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +                              if not '_defaults' in str(file)]
Probably you want to use `DEFAULTS_PATH` here to make it more future-proof.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +               else cls.is_matching_user_settings)
indent

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        obj_settings_files, _ = zip(
```suggestion
        # Sort by score, best first, and discard the scores
        obj_settings_files, _ = zip(
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        """Determine if the default settings file is for this instance.
```suggestion
        """Determine if a default `config` is for this instance.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        can fulfill this criteria.
```suggestion
        can fulfill this criterion.
```
or "these criteria"

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            The information that should be used to check 'config'.
```suggestion
            The information that should be used to check `config`.
```

The NumPy style suggests to use bacticks around argument names. This is so that they are formatted nicely in auto-generated documentation (e.g., via `sphinx`).

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            multiple files are found.
```suggestion
            A tuple that can be used to sort the detected settings.
            Larger values in the tuple indicate a higher degree of
            conformity. The order of the items in the tuple is the
            order of their significance. This return value is used
            to determine the best-matching settings files when
            multiple files are found.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        """Determine if the settings file is for this instance.
```suggestion
        """Determine if a `config` file is for this instance.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        match_exactly is true, the config has to be a perfect match
```suggestion
        match_exactly is True, the config has to be a perfect match
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            The information that should be used to check 'config'.
```suggestion
            The information that should be used to check `config`.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        This method must use obj_info to determine if a config is
```suggestion
        Subclasses must extend this method by calling
        super().is_matching_user_settings at the beginning.

        This method must use obj_info to determine if a config is
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        This method must use obj_info to determine if a config is
Otherwise the type check in the base class is lost.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +                )
```suggestion
                )
        return tuple()
```

It is good practice to return the right stuff already if you do have a non-empty implementation.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        """Determine if the settings file is for this class.
```suggestion
        """Determine if a `config` file is for this class.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        _mandatory_settings are present in the provided settings.
```suggestion
        Subclasses may add additional mandatory settings at
        runtime by modifying the self._mandatory_settings
        attribute before calling the base-class implementation.
        The base implementation checks whether all of the
        _mandatory_settings are present in `new_settings`.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            Invalid required_settings of self as a list of tuples.
```suggestion
            Invalid _mandatory_settings of self as a list of tuples.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        _mandatory_settings are present in the provided settings.
The fact that we allow **instances** to edit the **class attribute** `_mandatory_settings` is a bit risky: if one instance edits its `_mandatory_settings`, such an edit is reflected in all other instances as well as in all the instances of subclasses. We should discuss how to do this properly.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        return [(invalid,) for invalid in
Is this right? If it is, the description in the doscstring may be wrong: the return value is a list of 1-long tuples in the current implementation.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        try:                                                                    # TODO: make method that searches through invalid for old values and replaces deprecated ones, make it a method of the
Perhaps make an issue for this one so we can then prepare a dedicated PR

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            a length greater than 3.
This is a bit obscure.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        folder. Do not edit the files in the _defaults folder!
Perhaps add a little documentation on how items should look like.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        except(ValueError, NoSettingsError):
```suggestion
        except (ValueError, NoSettingsError):
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    """Abstract base class of hardware related objects."""
```suggestion
    """Abstract base class of hardware-related objects."""
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        """
Missing `Parameters` and `Returns` doc

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        Note that 'busy =' will be performed in the calling
```suggestion
        Note that 'self.busy =' will be performed in the calling
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        file for the device from it.
```suggestion
        This method must return a list of SettingsInfo instances. Each
        device is represented by a single SettingsInfo instance. The
        SettingsInfo object must contain a .unique_name and can contain
        .more information as a dict. The information contained within
        a SettingsInfo must be enough to determine a suitable settings
        file for the device from it.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        Unique name identifying the discovered device
```suggestion
        Unique name identifying the device.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        Extra, optional, information about the discovered device.
```suggestion
        Extra, optional, information about the device.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        Unique name identifying the discovered device
Not sure about removing "discovered": is this only coming from list_devices or can it be more general? Looks like it could be more general as `QObjectWithSettingsABC` takes instances of this as an argument to some methods, and `QObjectWithSettingsABC` instances do not have a `list_devices`.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/abc.py
> +                f"{n_frames} [out of range ({min_n}, {max_n})]",
```suggestion
                f'{n_frames} [out of range ({min_n}, {max_n})]',
```

Since we are at it...

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/abc.py
> +            "bad pixel" in error_msg):
```suggestion
        if (error is QObjectSettingsErrors.INVALID_SETTINGS
                and 'bad pixel' in error_msg):
```

Operators to "next line" when using continuation lines: you see immediately what the logic is (no need to go to the end of the previous line to find out if it was an "and", an "or", a "+", ....). When using "if (...", indent the continuation line 4 characters more so it's not aligned with the contents of the if block ("if (" is exactly 4 characters).

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/abc.py
> +        SettingsInfo object contains the uninque device name and a dict
Update doc, `SettingsInfo` is somewhere else now

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
>      ImagingSourceError, SinkFormat,
Would you mind splitting these one per line?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        """Determine if the default settings file is for this camera.
Update this `__doc__` from my comments on the abc

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +    def is_matching_default_settings(cls, obj_info, config, match_exactly):
```suggestion
    # pylint: disable-next=unused-argument  # From base-class signature
    def is_matching_default_settings(cls, obj_info, config, match_exactly):
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        know that the class matches.
Perhaps a few more words on why this is the case? Also, I would place this, and the extra words, in a comment right before the return. People doing `help(<this method>)` don't need to know that this one always returns "matching".

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        """Determine if the settings file is for this camera.
Also this one: update from my comments in abc

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        """Determine if the settings file is for this camera.
Same here with the `__doc__` update

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +MeasureController class abstract base classes used for giving basic
Please search-replace `MeasureController` with `MeasureControllerABC` to avoid confusion. We must have renamed it at some point and not updated the term everywhere.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +MeasureController class abstract base classes used for giving basic
Also:
MeasureController ~class~ abstract base classes used for giving basic

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +                                                 'serial_port_class')
Perhaps, after you have created the issue about the "auto-rename legacy settings" you could refer to it here instead of the comments? E.g.,

```python
...    # TODO: #<new_issue_nr>
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        serial_cls_name = self._settings.get('controller', 'serial_class',
Is there a reason why we use `self._settings` and not `self.settings` here? If yes, I'd mention why, otherwise it's probably nicer to use the public `@property`.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        _settings_serial = self._settings.get('controller', 'address',
This name is a bit unfortunate. Perhaps make it clearer that it is the address?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/abc.py
>          # Backwards compatibility fix
Add also here a `# TODO: #<new_issue_nr>` comment

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        to determine a suitable settings file for the device from it.
Update like abc

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +    obj_cls : object
```suggestion
    obj_cls : type
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
>          "a different directory."
To make it a little nicer, we could add info to this text if there is a `third_btn_text`, e.g.:

```python
msg = (f'Directory {directory} and its subfolders do not '
       f'contain any settings file for device {obj_name}. '
       'Select a different directory.')
if third_btn_text:
    msg += f' Alternatively, you can {third_btn_text.lower()}.'
msg_box.setText(msg)
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +    obj_cls : object
```suggestion
    obj_cls : type
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        settings. How exactly is up to the reimplementation of
```suggestion
        settings. How exactly is up to the implementation of
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        settings. How exactly is up to the reimplementation of
```suggestion
        settings. How exactly is up to the implementation of
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +            or not. What this entails is up to the reimplementation of
```suggestion
            or not. What this entails is up to the implementation of
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +            find_matching_settings_files. Default is False.
```suggestion
            obj_cls.find_matching_settings_files. Default is False.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        was given as a third_btn_text parameter, but the user anyway
If this thing about returning an empty string still applies, then the param type doc is inaccurate. See also my suggestion about using a module global higher up.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
>          return ""
I've never been a huge fan of returning an empty string here. Perhaps we should have a module global (somewhere in the dialogs modules?) like

```python
DIALOG_DISMISSED = object()
```

that can be imported

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +            "Select which one should be used:",
Would you mind replacing these double quotes with single ones?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +    'PC_CHANGE_MEAS_MODE', 'PC_STOP', 'PC_SET_VOLTAGE_ONLY', 'PC_SET_SERIAL_NR'
For easier future maintenance, could you have each of these on a line by itself? Also, would be good to have them sorted alphabetically.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +                            f"adc_update_rate/{update_rate_raw}", '')
```suggestion
                            f'adc_update_rate/{update_rate_raw}', '')
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        """Determine if the default settings file is for this controller.
Update `__doc__` from abc.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        """Determine if the settings file is for this controller.
Update `__doc__` from abc.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        """Determine if the settings file is for this controller.
Update `__doc__` from abc.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +            should be displayed. Default is False.
Missing: `config`, `parent`

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +    def __init__(self, config, parent=None, display_config=False):
The name is not so clear. Perhaps
```suggestion
    def __init__(self, config, parent=None, show_path_to_config=False):
```

or something of this kind.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +        None
```suggestion
        None.
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +
Move after `def add_section` for alphabetic sorting.

Also, since implementation is very similar to `add_section` (except for kwarg and raise), you could extract the common parts into a `def _add_section(self, section_name, **kwargs)` that you can use in both.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +                tooltip=str(file) if file else None,
Since `add_...` takes a string for `tooltip`, it may be better to give an empty string here rather than `None`.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
>                                                       v_align)
indent

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +            Other positional arguments  passed on to handler_widget
```suggestion
            Other positional arguments passed on to `handler_widget`
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +            Must be True, otherwise a RuntimeError is raised.
I think `ValueError` is the right exception here.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +        read_only : bool
Since it always is True, I would suggest making it optional. See also my edit below.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/dialogs/settingsdialog.py
> +        if kwargs.get('read_only') != True:
```suggestion
        kwargs.setdefault('read_only', True)
        if kwargs['read_only'] != True:
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +        return ()
Perhaps a little comment here to explain why you always return an empty tuple?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +        """Determine if the default settings file is for a measurement.
Update `__doc__` from abc.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +        is_suitable : bool
This type doc does not match with what you return

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +        is_suitable : bool
Same as previous

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +        """Determine if the settings file is for a measurement.
Update `__doc__` from abc.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +        # of the preparation to the exit point of the preparation,
```suggestion
        # of the preparation to the exit point of the preparation
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/measurement/energy_calibration.py
> +                '', 'measurement_settings/delta_energy', fallback
```suggestion
                '', 'measurement_settings/delta_energy', fallback,
```

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/measurement/energy_calibration.py
> +                '', 'measurement_settings/delta_energy', fallback
(Multiple occurrences)

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/serial/abc.py
> +        raise RuntimeError(f'{(self).__name__} was asked to perform a '
Probably here the right exception is `TypeError`. Also applies below.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/serial/viperleedserial.py
>              cmd_names.append("PC_DEBUG")
Would you mind changes these too to single quotes?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +            detected_devices = base.get_devices(device_type).items()
Do you need `.items()`? I would perhaps make the `detected_devices` above an empty dict and rather return a dict from this one. Then you can decide if you want to `return detected_devices.items()` or use `.items()` when you iterate through them.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/uimeasurement.py
>          device.settings[section]['device_name'] = device_name
Potential `NameError` if `section` is not defined (see conditions above). Perhaps add an `else` where you raise a `ValueError`?

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +        device.uses_default_settings = False
I now see why you made `.uses_default_settings` public. Discard my comments in `abc` concerning this.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +        cam_cls, cam_info = self.sender().data()
You probably don't need to unpack these. See my edit below.

2024-10-05 06:23 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +        camera = self.__make_device(cam_cls, cam_info)
```suggestion
        camera = self.__make_device(*self.sender().data())
```

2024-10-05 06:24 UTC, michele-riva commented
Please also make sure to merge in the base branch and resolve conflicts.

2024-10-09 12:02 UTC, FlorianDoerr commented on guilib/measure/camera/imagingsource.py
> +        """Determine if the default settings file is for this camera.
I updated the Sphinx related changes but left the rest, as this method only returns (1,) in any case.

2024-10-10 07:19 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            information on what is wrong with the setttings.
```suggestion
            information on what is wrong with the settings.
```

2024-10-10 07:20 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        try:                                                                    # TODO: make method that searches through invalid for old values and replaces deprecated ones, make it a method of the
I'd suggest to replace the TODO with `# TODO: #242`

2024-10-10 07:21 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +                                             fallback='')                       # TODO: #<242> (remove fallback in 1.0)
indent

2024-10-10 07:26 UTC, michele-riva requested changes
Sorry, I wanted to add single comments, but ended up clicking the wrong button and created another review.

2024-10-10 07:26 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +                                             fallback='')                       # TODO: #<242> (remove fallback in 1.0)
Also, probably better to have `# TODO: #242`, as we would probably search for "#242" to see where this is relevant. (Multiple occurrences.)

2024-10-10 07:26 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +            serial_cls_name = self.settings.get('controller',
Indent at L474

2024-10-10 07:26 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        SettingsInfo class is located in the classes abc module. Each
```suggestion
        SettingsInfo class is located in the classes.abc module. Each
```

2024-10-10 11:21 UTC, FlorianDoerr commented on guilib/measure/measurement/abc.py
> +        return ()
This just was not used and not implemented for measurements back then. Has been implemented in the measurement-settings-dialog branch.

2024-10-10 12:02 UTC, FlorianDoerr commented on guilib/measure/uimeasurement.py
> +            detected_devices = base.get_devices(device_type).items()
Let's decide if we want to rework this in the measurement-settings-dialog branch.

2024-10-11 09:16 UTC, michele-riva requested changes
Last round, I promise!

2024-10-11 09:16 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        if not serial_cls_name:                                                 # TODO: #242 (only here for backwards compatibility, remove in 1.0)
Once we have the aliases in place as in #242, I think we can leave this part in. I would remove the "remove XXX in 1.0"

2024-10-11 09:16 UTC, michele-riva commented on guilib/measure/dialogs/constants.py
> +DIALOG_DISMISSED = object()
Missing newline at the end

2024-10-11 09:16 UTC, michele-riva commented on guilib/measure/dialogs/constants.py
> +Defines constants used in the other ViPErLEED modules.
```suggestion
Defines dialog-related constants used in the other ViPErLEED modules.
```

2024-10-11 09:16 UTC, michele-riva commented on guilib/measure/dialogs/constants.py
> +"""Module constants of viperleed.guilib.measure.dialogs.
Consider if it makes sense to move this module "one level up", to guilib/dialogs

2024-10-11 09:16 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        pop-up. DIALOG_DISMISSED is returned if an alternative option
Add this to the type specification too (I cannot comment on that line):

```python
    path_to_config : Path or None or DIALOG_DISMISSED
```

2024-10-11 09:16 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +            A tuple that can be used the sort the detected settings.
```suggestion
            A tuple that can be used to sort the detected settings.
```

2024-10-11 09:16 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +            A tuple that can be used the sort the detected settings.
Multiple occurrences

2024-10-11 09:16 UTC, michele-riva commented on guilib/measure/measurement/abc.py
>          # Backwards compatibility fix for port_name:
Add a `# TODO: #242` here too

2024-10-13 02:26 UTC, michele-riva requested changes
Sorry Flo, some more suggestions/considerations now that I went again through the whole thing.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/camera/abc.py
> +            self.set_settings(self._settings_to_load)
Perhaps to add to your TODO list: We could consider whether this feature of "delaying errors" occurring at `__init__` is something that would make sense to move up the inheritance tree. Then all subclasses would have it. We should discuss how one could do that. Also, I would not do it now, but keep it for later.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/camera/abc.py
> +        # Checking of non-mandatory data is done in property getters.
```suggestion
        # Checking of non-mandatory data is done in property getters.
        # The base-class implementation takes care of _mandatory_settings.
```

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/constants.py
> +"""Module constants of viperleed.guilib.measure.
Move to guilib/dialogs

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +            A tuple that can be used to sort the detected settings.
Perhaps a note to add to all these docstrings (in the various classes): Returning an empty tuple signifies that `config` does not match.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +    def is_settings_for_this_class(cls, config):
This implementation seems pretty general. Would it make sense to move it to camera.abc?

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        handler.add_from_handler(super().get_settings_handler())
To avoid calling `check_creating_settings_handler_is_possible` explicitly, would it make sense to do this instead?

```suggestion
        base_handler = super().get_settings_handler()
        handler = SettingsHandler(self.settings, show_path_to_config=True)
        handler.add_from_handler(base_handler)
```

The `super()` call should should already `check_creating_settings_handler_is_possible`.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        self.settings = self._settings_to_load (or, equivalently,
```suggestion
        self.settings = self._settings_to_load, or, equivalently,
```

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            a TypeError will be raised.
This portion of the docstring seems out of place. I think this method always uses `is_matching_default_settings`.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/dialogs/badpxfinderdialog.py
> +        if (error is QObjectSettingsErrors.INVALID_SETTINGS
Would it make sense to use `self.active_camera.is_bad_pixels_error(error_info)`?

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/hardwarebase.py
>      return re.compile("|".join(r'^.*' + p + r'\s*$' for p in _patterns))
The reason why I originally had to "match toward the end of a line" is that we used to read the configuration file as a normal text file. I think now we can probably be more strict, as we always read the files with a Configparser. I would suggest to modify this to be forgiving only with empty spaces that may come before the stuff to match rather than "any character":

```suggestion
    return re.compile('|'.join(rf'^\s*{p}\s*$' for p in _patterns))
```

The critical bit is replacing `.*` (== match any character) with `\s*` (== match any space character).

(Notice also the use of an f-string to improve readability, and the "fix" for the double quote.)

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        anyway dismissed the dialog.
Maybe I would switch these two descriptions around: say first when DIALOG_DISMISSED is returned, then when None is. Otherwise it sounds funny and not so clear.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +def get_object_settings(obj_cls, obj_info, **kwargs):
Perhaps add a TODO for yourself about this: I would suggest we make a decorator that raises unless a function is executed in the main thread (I may have something already where `MainThreadDispatcher` is defined) and have this function decorated. Something like:


```python
def ensure_main_thread(func):
    """Raise InvalidThreadError if `func` runs in a non-GUI thread."""
    @wraps(func)
    def _wrapper(*args, **kwargs):
        current_thread = <find thread>
        if current_thread != <main thread>:
            raise InvalidThreadError(f'Called {func.__name__} in non-GUI thread.')
        return func(*args, **kwargs)
    return _wrapper
```

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/hardwarebase.py
>              for an extra button with "accept role" in the did-not-
I cannot add a comment to the following lines, but there is still a mention of the empty-string return value there.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +from viperleed.guilib.measure.constants import DIALOG_DISMISSED
Wrong spot for alphabetic sorting. Will need to be moved anyway when constants.py goes to `viperleed.guilib.dialogs`.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +                BadPixelsFinderDialog(),
Since this line is now short enough, you can move it next to the key one line up.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +                FirmwareUpgradeDialog(self),
This line is also short enough to go next to the key.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +                            str(err) + ' Contact the ViPErLEED team '
```suggestion
                            f'{err} Contact the ViPErLEED team '
```

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +        except SettingsError as err:
Now that I see this, perhaps in the `viperinocontroller` we should rather `raise SettingsError` instead of `RuntimeError`. Even better would be to have a dedicated `DefaultSettingsError(SettingsError)` exception.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +            # Something is wrong with the default configuration file.
Here we should do the same as in `viperinocontroller` or emit some error.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        anyway dismissed the dialog.
On second thought, there may be a nicer way to do this, using the "samurai approach" (i.e., succeed or "die"): we could raise exceptions rather than returning some "invalid" stuff. We could then make the DIALOG_DISMISSED case actually raise a `DialogDismissedError(DialogError)` exception that would be defined in `guilib.dialogs.errors`. The same could be done for the `None` case, raising some other exception. See also my comments below.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        return config
I would change this a bit:
```suggestion
        if dropdown.exec_() == dropdown.Apply:
            return device_config_files[names.index(dropdown.selection)]
        return DIALOG_DISMISSED  # or, actually, raise (see my suggestion above)
```

It feels like the case in which we found multiple ones but the user did not successfully select a file should be treated as a "they decided not to do stuff" rather than "we should make a new one from defaults".

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +                            str(err) + ' Contact the ViPErLEED team '
A good alternative would be to have the `DefaultSettingsError` have the "contact ..." part of the message already.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +            # Something is wrong with the default configuration file.
Perhaps the best would be to have a `_emit_default_faulty` decorator of the form:

```python
def _emit_default_faulty(func):
    """Emit an error_occurred when a _defaults settings file is wrong."""
    @wraps(func)
    def _wrapper(self, *args, **kwargs):
        try:
            return func(self, *args, **kwargs)
        except DefaultSettingsError as exc:
            self.emit_error(QObjectSettingsErrors.DEFAULT_SETTINGS_CORRUPTED, str(exc))
            raise
    return _wrapper
```

to be used around the methods that should emit:
- `__make_device`: raises here; `__make_ctrl_settings_dialog` catches `DefaultSettingsError` and returns instead of https://github.com/viperleed/viperleed/blob/b44879b440f76c1d1018ddc78d5fa49085b7a693/guilib/measure/uimeasurement.py#L640-L641 `__on_camera_clicked` behaves similarly.
- `_detect_devices`: does not catch the `DefaultSettingsError`s that are raised by `get_devices` (via the `.list_devices` of each class). `update_device_lists` takes care of the catching.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +        ctrl_name = ctrl_info.more['name']
Since this part is only relevant inside the if below, it would be better to place it there

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        sure to call super().find_default_settings at the end.
```suggestion
        If this method is extended in subclasses, make sure
        to call super().find_default_settings at the end.
```

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +        handler.add_from_handler(super().get_settings_handler())
Similar to the suggestion for camera, could one do:

```python
base_handler = super().get_settings_handler()
handler = SettingsHandler(self.settings, show_path_to_config=True)
...
handler.add_from_handler(base_handler)
...
```

I think this way we could probably avoid the calls to `.check_creating_settings_handler_is_possible` altogether, and we could simply remove it as a method.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +                raise RuntimeError(
See my notes in uimeasurement.py concerning which exception to raise here.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +            Invalid required_settings of self as a list of tuples.
We do not have a `required_settings` attribute. Perhaps just "required settings" or "mandatory settings"?

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +        return handler
We may just be able to use `super().get_settings_handler()` here if `SettingsHandler` would allow to pick whether the path is visible or not also after `__init__`. Maybe it is enough to make `show_path_to_config` a `@property` that does the right thing.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        sure to call super().find_default_settings at the end.
On second thought, I'm not sure we should advise to extend this method at all. The real mechanics happens in `find_matching_settings_files`. I would perhaps remove this bit of the docstring altogether.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        settings_files = Path(directory).resolve().glob('**/*.ini')
```suggestion
        directory = Path(directory).resolve()
        default = True if directory == DEFAULTS_PATH else False
        settings_files = directory.glob('**/*.ini')
```

just in case we get the path to default files as a string rather than via the `DEFAULTS_PATH` constant.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            config.read(settings_file)
```suggestion
            config = ViPErLEEDSettings.from_settings(settings_file)
```

Would it make sense to use a `ViPErLEEDSettings` right away here? Feels more natural, as this gives more options to the various methods in checking attributes (also in light of #242).

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        Reimplementations can add additional mandatory settings at
```suggestion
        Subclasses may add additional mandatory settings at
```

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        Reimplementations can add additional mandatory settings at
Perhaps an indication on how to do that would be useful. Either here or (better) in the description of the `_mandatory_settings` attribute above.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            information on what is wrong with the settings.
```suggestion
            Further optional entries may be added by subclasses. They
            specify additional information on what is wrong with each
            invalid setting.
```

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    def set_settings(self, new_settings):
Do we want to make this a `pyqtSlot`? If yes, make sure to propagate decoration to subclasses that extend this.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        try:                                                                    # TODO: make method that searches through invalid for old values and replaces deprecated ones, make it a method of the
```suggestion
        try:                                                                    # TODO: #242 make method that searches through invalid for old values and replaces deprecated ones, make it a method of the ViPErLEEDSettings class
```

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    def get_busy(self):
Do we want this to be public to the outside (i.e., not only in subclasses)? Perhaps better to make it a `_get_busy` instead? The only reason to make it public would be to make it also a `pyqtSlot`.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        file for the device from it.
Perhaps we should be more explicit as to what "suitable" means? It is a bit generic.

2024-10-13 02:26 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            Each element is a SettingsInfo instance containing the name
```suggestion
            Each item is a SettingsInfo instance containing the name
```

2024-10-14 08:15 UTC, FlorianDoerr commented on guilib/measure/camera/imagingsource.py
> +    def is_settings_for_this_class(cls, config):
I would only generalize this part once we see we can use it for other cameras aswell. Until then I would leave it here.

2024-10-14 09:24 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +    def is_settings_for_this_class(cls, config):
Sounds good. Then perhaps add a TODO next to this and one in camera.abc (probably at the top is enough) so we can find it again if we need it.

2024-10-14 09:27 UTC, FlorianDoerr commented on guilib/measure/camera/imagingsource.py
> +    def is_settings_for_this_class(cls, config):
Will do

2024-10-16 07:06 UTC, michele-riva requested changes
Thanks for the good work @FlorianDoerr. A few more minor changes. As discussed in person, those that are likely going to give conflicts can be done directly in the soon-to-be-completed #263. Please then resolve the conversations by referring to the SHA of the commit that implemented the change (even if it is in #263).

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/camera/abc.py
> +            self.set_settings(self._settings_to_load)
#257

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +            `config` file matches the requirements.
```suggestion
            multiple files are found. An empty tuple signifies that
            `config` does not match the requirements.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +        # relevant camara attributes taken from the settings files do
```suggestion
        # relevant camera attributes taken from the settings files do
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/camera/imagingsource.py
> +            `config` file matches the requirements.
```suggestion
            multiple files are found. An empty tuple signifies that
            `config` does no match the requirements.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    TooManyDefaultSettingsError,
Add a TODO for yourself to catch this one too in the `_emit_defaults_faulty` decorator.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            )
```suggestion
            )
        To add _mandatory_settings for an instance at runtime, use:
        self._mandatory_settings = (
            *type(self)._mandatory_settings,
            (<section>, <option>, (<value1>, <value2>, ...)),
            ...
            )
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        _settings_to_load will automatically be the best matching
```suggestion
        _settings_to_load will automatically be the best-matching
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    def check_creating_settings_handler_is_possible(self):
Add a TODO for yourself to make this private and rather use `super().get_settings_handler()` after the tags are present.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            settings without additional information, when searching for
```suggestion
            settings without additional information when searching for
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            information, when searching for default settings via
```suggestion
            information when searching for default settings via
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            conformity = is_matching(obj_info, config, match_exactly)
Perhaps a nicer name for this would be `score`?

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        from the object class itself. If match_exactly is true, the
```suggestion
        from the object class itself. If match_exactly is True, the
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            `config` file matches the requirements.
```suggestion
            multiple files are found. An empty tuple signifies that
            `config` does not match the requirements.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +            `config` file matches the requirements.
```suggestion
            multiple files are found. An empty tuple signifies that
            `config` does not match the requirements.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        _mandatory_settings are present in the provided settings.
```suggestion
        Subclasses may add additional mandatory settings at
        runtime. See the documentation of the _mandatory_settings
        attribute for how to do this. The base implementation will
        check if all of the _mandatory_settings are present in the
        provided settings.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +        handler.add_section, and handler.add_option methods.
```suggestion
        handler.add_section and handler.add_option methods.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/settings.py
> +class TooManyDefaultSettingsError(SettingsError):
Perhaps a better way to handle the catching of `DefaultSettingsError` would be to make `NoDefaultSettingsError` and `TooManyDefaultSettingsError` subclasses of `DefaultSettingsError`. Then it would be enough to catch the latter.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/classes/settings.py
> +                                  'load settings.') from exc
I cannot comment on the next lines, but you don't need the else after a raise.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/controller/abc.py
> +        return self._busy
```suggestion
        return super()._get_busy()
```

Just in case we ever change the `super()` method.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/controller/abc.py
>          may simply extend _mandatory_settings, then call super().
```suggestion
        may simply extend _mandatory_settings, then call super().
        See the documentation of the _mandatory_settings attribute
        in measure.classes.abc.QObjectWithSettingsABC for how to
        do this safely.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +            no `config` file matches the requirements.
```suggestion
            firmware minor will be preferred. An empty tuple signifies
            that `config` does not match the requirements.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +            requirements.
```suggestion
            firmware minor with a matching major will be preferred.
            An empty tuple signifies that `config` does not match
            the requirements.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/controller/viperinocontroller.py
> +            config.get('controller', 'firmware_version', fallback='0.0')
We to this several times. We should consider to add a `getversion` method to `ViPErLEEDSettings` that already returns a `base.Version` object.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        msg += f' Alternatively you can {third_btn_text.lower()}.'
```suggestion
        msg += f' Alternatively, you can {third_btn_text.lower()}.'
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/hardwarebase.py
>              directory=str(directory)
```suggestion
            directory=str(directory),
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +def get_object_settings(obj_cls, obj_info, **kwargs):
#262

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        The same arguments given to get_object_settings
```suggestion
        The same arguments given to get_object_settings. See
        help(get_object_settings) for more information.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        given.
```suggestion
        If no settings file was found and no alternative option was
        given, or if multiple files were found but the user did not
        pick one.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/hardwarebase.py
> +        raise NoSettingsError('No device settings selected.')
```suggestion
        raise NoSettingsError('Multiple setting files found. None selected.')
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/hardwarebase.py
>              dev_list = dummy_instance.list_devices()
I'd perhaps add a comment right above the call to `list_devices` to clarify that it is that call that raises `DefaultSettingsError`.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +            `config` file matches the requirements.
```suggestion
            multiple files are found. An empty tuple signifies that
            `config` does not match the requirements.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +            `config` file matches the requirements.
```suggestion
            multiple files are found. An empty tuple signifies that
            `config` does not match the requirements.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/measurement/abc.py
> +            the setttings.
Check consistency of this and the `__doc__` of other versions of this function. The one that says "optional" is probably the better one.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/serial/abc.py
>      # essentially unusable, apart from loading appropriate settings
Delete these wo lines, as they referred to the invalid- and missing-settings cases, which do not exist anymore.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/serial/abc.py
> +
Given that these three methods are identical, I'd suggest the following:
```suggestion
    @classmethod
    def _cannot_check_settings(cls, *_):
        """Raise TypeError as SerialABC settings come from controllers."""
        # Generally speaking controllers have to find the approriate
        # settings for their serial. Therefore this method should never
        # be called.
        raise TypeError(f'{cls.__name__} was asked to perform a '
                        'settings check. Serials should never determine '
                        'appropriate settings on their own.')

    is_matching_default_settings = _cannot_check_settings
    is_matching_user_settings = _cannot_check_settings
    is_settings_for_this_class = _cannot_check_settings
```

Notice also that you had a `NameError`, as `self` was not defined.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +        except (DefaultSettingsError, NoDefaultSettingsError) as exc:
If you do as I suggested above concerning hierarchy of exceptions, it is sufficient to catch `DefaultSettingsError` here to handle all cases at once.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +    """Emit an error_occurred when a _defaults settings file is wrong."""
```suggestion
    """Emit an error_occurred when a _defaults settings file has problems."""
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +            except (DefaultSettingsError, NoDefaultSettingsError):
Also here catching `DefaultSettingsError` is enough with exception subclassing.

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +            # No settings
```suggestion
            # No settings selected. Will make a new one from defaults.
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +            # The get_devices method does return the device name,
```suggestion
            # The _detect_devices method returns the device name,
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +        device_name = settings_info.more['name'] or settings_info.unique_name
Is there a potential for a `KeyError` here? If yes, use

```suggestion
        device_name = settings_info.more.get('name') or settings_info.unique_name
```

2024-10-16 07:06 UTC, michele-riva commented on guilib/measure/uimeasurement.py
> +                source = f'measurement {sender.__class__.__name__}'
```suggestion
                source = f'measurement {type(sender).__name__}'
```

For consistency with the `SerialABC` condition

2024-10-16 07:08 UTC, michele-riva commented on guilib/measure/classes/abc.py
> +    TooManyDefaultSettingsError,
Actually, not needed if you do as I suggest below concerning subclassing of `DefaultSettingsError.`

2024-10-16 16:19 UTC, michele-riva approved these changes
Looks good!

2024-10-16 16:22 UTC, merged